package com.ziroom.ssm.po;

import java.util.Date;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.product_date
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    private Date productDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.shelf_life
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    private Integer shelfLife;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.description
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.pic
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    private String pic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.product_date
     *
     * @return the value of goods.product_date
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    public Date getProductDate() {
        return productDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.product_date
     *
     * @param productDate the value for goods.product_date
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    public void setProductDate(Date productDate) {
        this.productDate = productDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.shelf_life
     *
     * @return the value of goods.shelf_life
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    public Integer getShelfLife() {
        return shelfLife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.shelf_life
     *
     * @param shelfLife the value for goods.shelf_life
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    public void setShelfLife(Integer shelfLife) {
        this.shelfLife = shelfLife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.description
     *
     * @return the value of goods.description
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.description
     *
     * @param description the value for goods.description
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.pic
     *
     * @return the value of goods.pic
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.pic
     *
     * @param pic the value for goods.pic
     *
     * @mbggenerated Fri Jun 17 09:41:58 CST 2016
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }
}